Repository AY2021S1-CS2103-F10-4/tp, pull requests merged in 2020-10, with the labels that each got.

#35 Add Shift class and related data modelling classes
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/shift/RoleRequirement.java
  src/main/java/seedu/address/model/shift/Shift.java
  src/main/java/seedu/address/model/shift/ShiftDay.java
  src/main/java/seedu/address/model/shift/ShiftTime.java
  src/main/java/seedu/address/model/shift/UniqueShiftList.java
  src/main/java/seedu/address/model/shift/exceptions/DuplicateShiftException.java
  src/main/java/seedu/address/model/shift/exceptions/ShiftNotFoundException.java
  src/main/java/seedu/address/model/tag/Role.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRole.java
  src/main/java/seedu/address/storage/JsonAdaptedRoleRequirement.java
  src/main/java/seedu/address/storage/JsonAdaptedShift.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: class.Shift

#40 Add Pay class, edited Person to have Pay instead of Email
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Pay.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: class.Worker

#39 Add Shift-List Command
  src/main/java/seedu/address/logic/commands/ShiftListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: class.Shift

#100 Update Leave Implementation, Tests and Documentation.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LeaveClassDiagram.puml
  docs/diagrams/LeaveCommandsSequenceDiagram.puml
  docs/diagrams/MassTakeLeaveActivityDiagram.puml
  docs/images/LeaveClassDiagram.png
  docs/images/LeaveCommandsSequenceDiagram.png
  docs/images/MassTakeLeaveActivityDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CancelLeaveCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/MassCancelLeaveCommand.java
  src/main/java/seedu/address/logic/commands/MassTakeLeaveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CancelLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/MassCancelLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/MassTakeLeaveCommandParser.java
  src/main/java/seedu/address/logic/parser/TakeLeaveCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/address/model/shift/Shift.java
  src/main/java/seedu/address/model/shift/ShiftDay.java
  src/main/java/seedu/address/model/shift/ShiftTime.java
  src/main/java/seedu/address/model/worker/Worker.java
  src/test/java/seedu/address/logic/commands/CancelLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MassCancelLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/MassTakeLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/ShiftAddCommandTest.java
  src/test/java/seedu/address/logic/commands/TakeLeaveCommandTest.java
  src/test/java/seedu/address/logic/commands/WorkerAddCommandTest.java
  src/test/java/seedu/address/logic/parser/CancelLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MassCancelLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MassTakeLeaveCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TakeLeaveCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalShifts.java
Labels: class.Assignment, priority.Medium, type.Story

#119 Fix bug where role is case-sensitive
  src/main/java/seedu/address/logic/commands/UnassignCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ShiftEditCommandTest.java
  src/test/java/seedu/address/logic/commands/WorkerEditCommandTest.java
Labels: severity.High, type.Bug

#98 adjust ui: colors, jingle, icon, fix whitespace
  build.gradle
  src/main/java/mcscheduler/ui/JinglePlayer.java
  src/main/java/mcscheduler/ui/UiManager.java
  src/main/resources/images/mclogo.png
  src/main/resources/sounds/mcjingle.mp3
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/McTheme.css
  src/test/java/mcscheduler/commons/util/AppUtilTest.java
Labels: priority.Medium, type.Enhancement

#127 Update leave commands in user guide
  docs/UserGuide.md
Labels: type.Task
